# Generated by Django 5.0.6 on 2025-04-03 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_order_cart_items_order_food_item_order_price_and_more'),
        ('vendor', '0008_alter_fooditem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.canteenvendor'),
        ),
    ]
