# Generated by Django 5.1.4 on 2025-04-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='suject',
            new_name='subject',
        ),
    ]
