# Generated by Django 5.0.6 on 2025-04-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_rename_suject_contactus_subject'),
        ('customer', '0007_order_updated_at'),
        ('vendor', '0010_remove_offlineorder_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.fooditem')),
            ],
            options={
                'unique_together': {('customer', 'food_item')},
            },
        ),
    ]
