# Generated by Django 5.0.6 on 2025-04-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_rating'),
        ('customer', '0007_order_updated_at'),
        ('vendor', '0010_remove_offlineorder_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='vendor.fooditem')),
            ],
            options={
                'unique_together': {('food_item', 'customer')},
            },
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
